
artifact_evaluation_appendix_V20220119.pdf: artifact_evaluation_appendix_V20220119.tex
	pdflatex artifact_evaluation_appendix_V20220119.tex
	pdflatex artifact_evaluation_appendix_V20220119.tex

clean:
	rm -f *.pdf *.log *.out *.aux
